# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import imx708_pb2 as imx708__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imx708_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Imx708ServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/imx708.Imx708Service/GetStatus',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.SensorStatus.FromString,
                _registered_method=True)
        self.StartStream = channel.unary_unary(
                '/imx708.Imx708Service/StartStream',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StopStream = channel.unary_unary(
                '/imx708.Imx708Service/StopStream',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SoftReset = channel.unary_unary(
                '/imx708.Imx708Service/SoftReset',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetModes = channel.unary_unary(
                '/imx708.Imx708Service/GetModes',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.ModeList.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/imx708.Imx708Service/SetMode',
                request_serializer=imx708__pb2.ModeInfo.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetGain = channel.unary_unary(
                '/imx708.Imx708Service/GetGain',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.GainConfig.FromString,
                _registered_method=True)
        self.SetGain = channel.unary_unary(
                '/imx708.Imx708Service/SetGain',
                request_serializer=imx708__pb2.GainConfig.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetExposure = channel.unary_unary(
                '/imx708.Imx708Service/GetExposure',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.ExposureConfig.FromString,
                _registered_method=True)
        self.SetExposure = channel.unary_unary(
                '/imx708.Imx708Service/SetExposure',
                request_serializer=imx708__pb2.ExposureConfig.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetHdr = channel.unary_unary(
                '/imx708.Imx708Service/GetHdr',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.HdrConfig.FromString,
                _registered_method=True)
        self.SetHdr = channel.unary_unary(
                '/imx708.Imx708Service/SetHdr',
                request_serializer=imx708__pb2.HdrConfig.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetTestPattern = channel.unary_unary(
                '/imx708.Imx708Service/GetTestPattern',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.TestPatternConfig.FromString,
                _registered_method=True)
        self.SetTestPattern = channel.unary_unary(
                '/imx708.Imx708Service/SetTestPattern',
                request_serializer=imx708__pb2.TestPatternConfig.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetImageProcessing = channel.unary_unary(
                '/imx708.Imx708Service/GetImageProcessing',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.ImageProcessingConfig.FromString,
                _registered_method=True)
        self.SetImageProcessing = channel.unary_unary(
                '/imx708.Imx708Service/SetImageProcessing',
                request_serializer=imx708__pb2.ImageProcessingConfig.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.CaptureFrame = channel.unary_unary(
                '/imx708.Imx708Service/CaptureFrame',
                request_serializer=imx708__pb2.CaptureParams.SerializeToString,
                response_deserializer=imx708__pb2.FrameData.FromString,
                _registered_method=True)
        self.CaptureFrames = channel.unary_stream(
                '/imx708.Imx708Service/CaptureFrames',
                request_serializer=imx708__pb2.CaptureParams.SerializeToString,
                response_deserializer=imx708__pb2.FrameData.FromString,
                _registered_method=True)
        self.SaveProfile = channel.unary_unary(
                '/imx708.Imx708Service/SaveProfile',
                request_serializer=imx708__pb2.Profile.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.LoadProfile = channel.unary_unary(
                '/imx708.Imx708Service/LoadProfile',
                request_serializer=imx708__pb2.Profile.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_stream(
                '/imx708.Imx708Service/ListProfiles',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.Profile.FromString,
                _registered_method=True)
        self.ReadRegister = channel.unary_unary(
                '/imx708.Imx708Service/ReadRegister',
                request_serializer=imx708__pb2.RegisterAccess.SerializeToString,
                response_deserializer=imx708__pb2.RegisterAccess.FromString,
                _registered_method=True)
        self.WriteRegister = channel.unary_unary(
                '/imx708.Imx708Service/WriteRegister',
                request_serializer=imx708__pb2.RegisterAccess.SerializeToString,
                response_deserializer=imx708__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/imx708.Imx708Service/StreamStatus',
                request_serializer=imx708__pb2.Empty.SerializeToString,
                response_deserializer=imx708__pb2.StatusStreamEvent.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/imx708.Imx708Service/StreamFrames',
                request_serializer=imx708__pb2.CaptureParams.SerializeToString,
                response_deserializer=imx708__pb2.FrameData.FromString,
                _registered_method=True)


class Imx708ServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def GetStatus(self, request, context):
        """=== Basic Control ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SoftReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModes(self, request, context):
        """=== Modes ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGain(self, request, context):
        """=== Gain / Exposure ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExposure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExposure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHdr(self, request, context):
        """=== HDR ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHdr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestPattern(self, request, context):
        """=== Test Pattern ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTestPattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageProcessing(self, request, context):
        """=== Image Processing ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetImageProcessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureFrame(self, request, context):
        """=== Capture ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProfile(self, request, context):
        """=== Profiles ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRegister(self, request, context):
        """=== Register Access (debug) ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """=== Streaming Telemetry ===
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Imx708ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.SensorStatus.SerializeToString,
            ),
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'SoftReset': grpc.unary_unary_rpc_method_handler(
                    servicer.SoftReset,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetModes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModes,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.ModeList.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=imx708__pb2.ModeInfo.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetGain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGain,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.GainConfig.SerializeToString,
            ),
            'SetGain': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGain,
                    request_deserializer=imx708__pb2.GainConfig.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetExposure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExposure,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.ExposureConfig.SerializeToString,
            ),
            'SetExposure': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExposure,
                    request_deserializer=imx708__pb2.ExposureConfig.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetHdr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHdr,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.HdrConfig.SerializeToString,
            ),
            'SetHdr': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHdr,
                    request_deserializer=imx708__pb2.HdrConfig.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetTestPattern': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestPattern,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.TestPatternConfig.SerializeToString,
            ),
            'SetTestPattern': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTestPattern,
                    request_deserializer=imx708__pb2.TestPatternConfig.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'GetImageProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageProcessing,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.ImageProcessingConfig.SerializeToString,
            ),
            'SetImageProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetImageProcessing,
                    request_deserializer=imx708__pb2.ImageProcessingConfig.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'CaptureFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureFrame,
                    request_deserializer=imx708__pb2.CaptureParams.FromString,
                    response_serializer=imx708__pb2.FrameData.SerializeToString,
            ),
            'CaptureFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.CaptureFrames,
                    request_deserializer=imx708__pb2.CaptureParams.FromString,
                    response_serializer=imx708__pb2.FrameData.SerializeToString,
            ),
            'SaveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProfile,
                    request_deserializer=imx708__pb2.Profile.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'LoadProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadProfile,
                    request_deserializer=imx708__pb2.Profile.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.Profile.SerializeToString,
            ),
            'ReadRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRegister,
                    request_deserializer=imx708__pb2.RegisterAccess.FromString,
                    response_serializer=imx708__pb2.RegisterAccess.SerializeToString,
            ),
            'WriteRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteRegister,
                    request_deserializer=imx708__pb2.RegisterAccess.FromString,
                    response_serializer=imx708__pb2.CommandResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=imx708__pb2.Empty.FromString,
                    response_serializer=imx708__pb2.StatusStreamEvent.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=imx708__pb2.CaptureParams.FromString,
                    response_serializer=imx708__pb2.FrameData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imx708.Imx708Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imx708.Imx708Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Imx708Service(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetStatus',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.SensorStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/StartStream',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/StopStream',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SoftReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SoftReset',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetModes',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.ModeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetMode',
            imx708__pb2.ModeInfo.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetGain',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.GainConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetGain',
            imx708__pb2.GainConfig.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExposure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetExposure',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.ExposureConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExposure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetExposure',
            imx708__pb2.ExposureConfig.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHdr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetHdr',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.HdrConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHdr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetHdr',
            imx708__pb2.HdrConfig.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetTestPattern',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.TestPatternConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTestPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetTestPattern',
            imx708__pb2.TestPatternConfig.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/GetImageProcessing',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.ImageProcessingConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetImageProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SetImageProcessing',
            imx708__pb2.ImageProcessingConfig.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/CaptureFrame',
            imx708__pb2.CaptureParams.SerializeToString,
            imx708__pb2.FrameData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imx708.Imx708Service/CaptureFrames',
            imx708__pb2.CaptureParams.SerializeToString,
            imx708__pb2.FrameData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/SaveProfile',
            imx708__pb2.Profile.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/LoadProfile',
            imx708__pb2.Profile.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imx708.Imx708Service/ListProfiles',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.Profile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/ReadRegister',
            imx708__pb2.RegisterAccess.SerializeToString,
            imx708__pb2.RegisterAccess.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imx708.Imx708Service/WriteRegister',
            imx708__pb2.RegisterAccess.SerializeToString,
            imx708__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imx708.Imx708Service/StreamStatus',
            imx708__pb2.Empty.SerializeToString,
            imx708__pb2.StatusStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imx708.Imx708Service/StreamFrames',
            imx708__pb2.CaptureParams.SerializeToString,
            imx708__pb2.FrameData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
